development:
  adapter: postgresql
  encoding: unicode
  database: test_case_heystack_dev_db
  pool: 5
  username: iamraghu
  password: iamraghu
  host: localhost
  port: 5432
production:
  adapter: postgresql
  encoding: unicode
  database: test_case_heystack_prod_db
  pool: 5
  username: iamraghu
  password: iamraghu
  host: localhost
  port: 5432